// <auto-generated />
namespace JSAGROAllegroSync.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Datetime2ColumnChange : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datetime2ColumnChange));
        
        string IMigrationMetadata.Id
        {
            get { return "202508241131173_Datetime2ColumnChange"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
